### PR TITLE
fix compilation error due to Rust/C type mismatches

### PR DESCRIPTION
**Pull request by pgerber**
Most errors where found when compiling on armv7-unknown-linux-gnueabihf
but there may be more type mismatches, I haven't thoroughly checked.

• change i8 to c_char for pointers to CString (c_char is unsigned
  on some architectures)
• change i64 to t_time where it represents a timestamp (t_time is
  32 bit on on 32 Architectures, at least on Linux)
• change a few other types to the correct C type

### CODE REVIEW

**Comment by cholcombe973** [comment]
Hey thanks for this!  I haven't had a chance to compile this on armv7.  Great work

**Comment by cholcombe973** [comment]
@hanscj1 could you do a release?  I don't think I have access to release to this package on crates.io.  I bumped the version a minor version but maybe it should be a major since we're changing types in this which will break clients potentially.

**Comment by hanscj1** [comment]
Sure enough.

**Comment by hanscj1** [comment]
done

**Comment by cholcombe973** [comment]
Sweet! Thanks.  Thank you also Peter :)

**Pull request merged**
