### PR TITLE
Add a small subset of ceph commands

### PR DESCRIPTION
**Pull request by cholcombe973**
Adding some commands into the library to allow people to interact with ceph without calling the cli through a shell command.

### CODE REVIEW

**Comment by cholcombe973** [comment]
@hanscj1 want to cut another release?  I've fixed a few bugs and added some functionality :)

**Comment by hanscj1** [comment]
Sure thing!

**Comment by cholcombe973** [comment]
I have one more fn I’m going to add shortly. Probably in the next day or
so.

**Comment by hanscj1** [comment]
Hmm, what version of Rust are you using? I have 1.22.0 nightly and running
into the following:

error[E0432]: unresolved import `ceph`
 --> src/cmd.rs:8:5
  |
8 | use ceph::ceph_mon_command_without_data;
  |     ^^^^ Maybe a missing `extern crate ceph;`?

**Comment by cholcombe973** [comment]
1.20 stable. I probably didn’t check something properly before merging.
Whoops. I’ll fix it tonight

**Comment by hanscj1** [comment]
Actually, it's missing the linux guard for cmd.rs and I wasn't thinking and
did it in OSX by default.

**Comment by cholcombe973** [comment]
So does cmd.rs need that linux guard at the top of it also?

**Comment by cholcombe973** [comment]
You know I should be using the proper error types here also.  Yeah let me fix this up and put up another PR.  This is a bit sloppy

**Comment by cholcombe973** [comment]
Ok new PR is up!

**Pull request merged**
